In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
desc = df['description']
desc = pd.DataFrame(desc)
desc

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 1 columns]

In [4]:
sampledesc = desc.loc[1, 'description']
print(type(sampledesc))
print(sampledesc)

<class 'str'>
After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.

In [5]:
import re

def rem_single_letters(df):
    pattern = r'\s[a-zA-Z]\s'
    df['description'] = [re.sub(pattern, ' ', str(x)) for x in df['description']]

def rem_unwanted_chars(df):
    pattern = r'[\!\@\#\$\%\^\&\*\(\)\-\_\+\=\/\.\,]'
    df['description'] = [re.sub(pattern, ' ', str(x)) for x in df['description']]

def conv_to_lowercase(df):
    df['description'] = df['description'].str.lower()

def rem_extra_spaces(df):
    pattern = r'\s{2}'
    df['description'] = [re.sub(pattern, ' ', str(x)) for x in df['description']]

In [6]:
def clean_text(desc):
    conv_to_lowercase(desc)
    rem_single_letters(desc)
    rem_unwanted_chars(desc)
    rem_extra_spaces(desc)

In [7]:
print(desc.loc[5, 'description'])
clean_text(desc)
print(desc.loc[5, 'description'])

The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.
the arrival of charismatic young priest brings glorious miracles ominous mysteries and renewed religious fervor to dying town desperate to believe

In [9]:
import nltk
nltk.download('stopwords')
stop = stopwords.words('english')
pattern = r'\b(?:{})\b'.format('|'.join(stop)) #taken from SOF
desc['description'] = desc['description'].str.replace(pattern, '')
rem_extra_spaces(desc)
desc

[nltk_data] Downloading package stopwords to /home/ujwal/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
<ipython-input-9-bb9a759f2bf1>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  desc['description'] = desc['description'].str.replace(pattern, '')

                                            description
0      father nears end  life filmmaker kirsten john...
1      crossing paths party cape town teen sets  pro...
2      protect family powerful drug lord skilled thi...
3     feuds flirtations toilet talk go among incarce...
4      city coaching centers known train indiaâ€™ fine...
...                                                 ...
8802   political cartoonist crime reporter pair cops...
8803   living alone spooky town young girl befriends...
8804  looking survive world taken  zombies dorky col...
8805  dragged civilian life former superhero must tr...
8806   scrappy poor boy worms way tycoon' dysfunctio...

[8807 rows x 1 columns]

In [12]:
!pip install num2words

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: num2words in /home/ujwal/anaconda3/lib/python3.9/site-packages (0.5.10)
Requirement already satisfied: docopt>=0.6.2 in /home/ujwal/anaconda3/lib/python3.9/site-packages (from num2words) (0.6.2)

In [18]:
from num2words import num2words
num2words(100)

def num_to_words(df):
    pattern = r'(\d+)'
    df['description'] = [re.sub(pattern, lambda a: num2words(int(a.group(0))), str(x)) for x in df['description']]

num_to_words(desc)
desc

                                            description
0      father nears end  life filmmaker kirsten john...
1      crossing paths party cape town teen sets  pro...
2      protect family powerful drug lord skilled thi...
3     feuds flirtations toilet talk go among incarce...
4      city coaching centers known train indiaâ€™ fine...
...                                                 ...
8802   political cartoonist crime reporter pair cops...
8803   living alone spooky town young girl befriends...
8804  looking survive world taken  zombies dorky col...
8805  dragged civilian life former superhero must tr...
8806   scrappy poor boy worms way tycoon' dysfunctio...

[8807 rows x 1 columns]